### ISSUE TITLE
Errors in rule edger_normalize_features

### ISSUE THREAD

**Issue by Dries-B** [NBISweden/nbis-meta#30]
Error message in `results/annotation/"$sample"/enzymes.parsed.CSS.log`:

```
Error in if (nrow(x) == 0) { : argument is of length zero
Calls: process_data
Execution halted
```

Error message in ` results/annotation/"$sample"/modules.parsed.CSS.log`:

```
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  duplicate 'row.names' are not allowed
Calls: read.delim -> read.table
Execution halted
```

**NOTE**: these errors occur while running a workflow based upon 49dd582b3e5f03203da3a0fe7cb0e6f6f3559584, which is behind current commit e574e79c7c187c33a04fe44aeab8bbd7a121111c.

**Comment by Dries-B** [comment]
```
$ cut results/annotation/"$sample"/modules.parsed.counts.tsv -f 1 | sort | uniq -d
Phthalate degradation, phthalate => protocatechuate [PATH:map00624 map01220 map01100 map01120]
```
Indeed, a module name seem to be duplicated.
```
$ grep 'Phthalate degradation' resources/kegg/kegg_modules.tsv 
M00623  Phthalate degradation, phthalate => protocatechuate [PATH:map00624 map01220 map01100 map01120]  Pathway modules Xenobiotics biodegradation  Aromatics degradation
M00636  Phthalate degradation, phthalate => protocatechuate [PATH:map00624 map01220 map01100 map01120]  Pathway modules Xenobiotics biodegradation  Aromatics degradation
```
So this might be resolved by including the module number in the module name.

Contrary to what I expected, `resources/kegg/kegg_modules.tsv` has changed since a previous analysis, but the lines returned by the previous code block have not been altered.

**Comment by Dries-B** [comment]
Looking further into this, I have found that my previous analysis did not include both `M00623  Phthalate degradation ...` and `M00636  Phthalate degradation ...`.

So perhaps other analyses had the same luck? What do you think?

In that case, pasting together the module code with the module name would already resolve the issue.

**Comment by Dries-B** [comment]
I am not sure yet what causes the "length zero" problem and will continue looking into this.

**Comment by johnne** [comment]
Thanks for reporting this Dries. Comparing the two commits there's been some updates to the code, and I vaguely remember running into these errrors. I think that a fix for this is already on the `develop` branch.

**Comment by Dries-B** [comment]
Okay, I will try merging (locally) into the `develop` branch then.
