### ISSUE TITLE
Could `units` in `samples.tsv` accept strings instead of only integers?

### ISSUE THREAD

**Issue by Dries-B** [NBISweden/nbis-meta#31]
Currently, when assembling different sequencing runs of the same sample, I have to convert those run codes to integers. Changing the type of `units` to string would circumvent this.

**Comment by johnne** [comment]
Hi @Dries-B 
Very late from my side. But when making a few updates to the workflow I've removed the requirement on `units`. See [7dcbc6d](https://github.com/NBISweden/nbis-meta/commit/7dcbc6d6bdc3c6bd3df635c82bab3f632b0796f6) . Currently only on the development branch, but will soon merge to main and create a new release
